### ISSUE TITLE
Privacy and IT security

### ISSUE THREAD

**Issue by FrankGrimm** [wegzwei/coronago#1]
Hallo zusammen,

https://corona-go.de/wegzwei-veroffentlicht-corona-go-beta-bluetooth-tracking-app-in-zusammenarbeit-mit-der-staatskanzlei-des-landes-saarland/ sagt "Die Corona GO App (BETA) ist mit den Grundsätzen des Pepp-PT Projekts konform". Laut Code werden scheinbar alle Meetings serverseitig gespeichert und mit einer simplen Auto-Increment UserId versehen, was genau ist daran GDPR compliant? Die NutzerInnen haben keinerlei Auditmöglichkeit über den Endpunkt der von der App verwendet wird und im Gegensatz zu vielen anderen App-Anstrengungen in dem Bereich des Contact Tracing scheint hier eine feste Id nicht nur zwischen UserIn und Server, sondern auch zwischen den einzelnen UserInnen ausgetauscht zu werden. Ausserdem ist in der Datenbanktabelle scheinbar nicht nur RSSI Values von der Bluetooth Hardware enthalten, sondern auch die Geoposition. Das würde die Erstellung von Bewegungsprofilen trivial machen. Zu Datenlöschung und Pseudonymisierung vor der Speicherung sehe ich in der Serverimplementierung dieses Repositories auch nicht wirklich etwas.

Und da das ja hoffentlich noch nicht ausgerollt ist: Ist das hier die aktuelle Implementierung der Serverkomponente unter api.corona-go.de?
https://github.com/wegzwei/coronago/blob/master/server-files/corona-go-server/routes/index.js
Die ist voller SQL Injection Vulnerabilities, fast keines der parametrisierten SQL Statements darin ist korrekt / sicher implementiert.

**Comment by wegzwei** [comment]
Es handelt sich hierbei um Beispielcode für eine Serverkomponente, die aufgrund des bevorzugten dezentralen Ansatzes (https://github.com/DP-3T/documents) in Kürze vom Netz genommen wird. In sofern: Ball flach halten, vielen Dank :)

**Comment by wegzwei** [comment]
Lieber @FrankGrimm 

vielen Dank für das Feedback und die beeindruckend schnelle Analyse. Das ist genau der Grund, warum wir uns den anderen Projekten angeschlossen haben. Die angesprochenen Punkte sind aus unserer Sicht in der Umsetzung das kleinere Problem, das war eben unser erster Ansatz.

Viel schwieriger ist es die Backgroundmodi und Bluetooth Kommunikation in den Griff zu bekommen, darum dreht sich unsere Veröffentlichung in erster Linie.

Die Serverarchitektur ist sekundär und wird in der Form in Kürze nicht mehr existieren.

**Comment by FrankGrimm** [comment]
Achso, super. Auf Hardwareseite haben Google und Apple gerade eine BT Erweiterung veröffentlicht falls ihr das noch nicht gesehen haben solltet, ist wohl ab Mai verfügbar:

https://www.apple.com/newsroom/2020/04/apple-and-google-partner-on-covid-19-contact-tracing-technology/ Crypto Specs: https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-CryptographySpecification.pdf

Ich schließe den Issue hier dann mal.
